<?php

namespace ContainerXhl6yKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WuL80HdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wuL80Hd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wuL80Hd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'markRepository' => ['privates', 'App\\Repository\\MarkRepository', 'getMarkRepositoryService', true],
            'recipe' => ['privates', '.errored..service_locator.wuL80Hd.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.wuL80Hd": it needs an instance of "App\\Entity\\Recipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'manager' => '?',
            'markRepository' => 'App\\Repository\\MarkRepository',
            'recipe' => 'App\\Entity\\Recipe',
        ]);
    }
}
