<?php

namespace ContainerXhl6yKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P56apcUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p56apcU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p56apcU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'postRepository' => ['privates', 'App\\Repository\\Post\\PostRepository', 'getPostRepositoryService', true],
            'tag' => ['privates', '.errored..service_locator.p56apcU.App\\Entity\\Post\\Tag', NULL, 'Cannot autowire service ".service_locator.p56apcU": it needs an instance of "App\\Entity\\Post\\Tag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'postRepository' => 'App\\Repository\\Post\\PostRepository',
            'tag' => 'App\\Entity\\Post\\Tag',
        ]);
    }
}
