<?php

namespace ContainerXhl6yKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Go7IyjUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.go7IyjU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.go7IyjU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recipeRepository' => ['privates', 'App\\Repository\\RecipeRepository', 'getRecipeRepositoryService', true],
        ], [
            'recipeRepository' => 'App\\Repository\\RecipeRepository',
        ]);
    }
}
