<?php

namespace ContainerXhl6yKC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G0UfuGH.App\Entity\Ingredient' shared service.
     *
     * @return \App\Entity\Ingredient
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G0UfuGH": it needs an instance of "App\\Entity\\Ingredient" but this type has been excluded in "config/services.yaml".');
    }
}
