<?php

namespace Container9cl4nCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ia0_R3CService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ia0.R3C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ia0.R3C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['privates', '.errored.BULUhdo', NULL, 'Cannot determine controller argument for "App\\Controller\\IngredientController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'repository' => ['privates', '.errored.FKGCAlN', NULL, 'Cannot determine controller argument for "App\\Controller\\IngredientController::index()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Repository\\IngredientRepository".'],
        ], [
            'paginator' => '?',
            'repository' => '?',
        ]);
    }
}
