<?php

namespace Container9cl4nCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__7QyXhDService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..7QyXhD' shared service.
     *
     * @return \App\Repository\RecipeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecipeController::indexPublic()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecipeRepository".');
    }
}
