<?php

namespace Container9cl4nCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FKGCAlNService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.FKGCAlN' shared service.
     *
     * @return \App\Repository\IngredientRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\IngredientController::index()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Repository\\IngredientRepository".');
    }
}
