<?php

namespace Container9cl4nCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FormRepository' shared autowired service.
     *
     * @return \App\Repository\FormRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FormRepository'] = new \App\Repository\FormRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
