<?php

namespace Container9cl4nCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormFRRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FormFRRepository' shared autowired service.
     *
     * @return \App\Repository\FormFRRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FormFRRepository'] = new \App\Repository\FormFRRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
