<?php

namespace Container9cl4nCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Autocomplete_ChoiceTypeExtensionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.autocomplete.choice_type_extension' shared service.
     *
     * @return \Symfony\UX\Autocomplete\Form\AutocompleteChoiceTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ux.autocomplete.choice_type_extension'] = new \Symfony\UX\Autocomplete\Form\AutocompleteChoiceTypeExtension(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
