<?php

namespace ContainerK0q7Nzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_EYYmqIService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.e_yYmqI' shared service.
     *
     * @return \Knp\Component\Pager\PaginatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecipeController::indexPublic()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".');
    }
}
