<?php

namespace ContainerK0q7Nzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGKSxh4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.QGKSxh4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QGKSxh4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['privates', '.errored.sV4PkFK', NULL, 'Cannot determine controller argument for "App\\Controller\\RecipeController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'repository' => ['privates', '.errored.r.n8F2B', NULL, 'Cannot determine controller argument for "App\\Controller\\RecipeController::index()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecipeRepository".'],
        ], [
            'paginator' => '?',
            'repository' => '?',
        ]);
    }
}
