<?php

namespace ContainerK0q7Nzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DwmU2lmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.DwmU2lm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DwmU2lm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['privates', '.errored.e_yYmqI', NULL, 'Cannot determine controller argument for "App\\Controller\\RecipeController::indexPublic()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'repository' => ['privates', '.errored..7QyXhD', NULL, 'Cannot determine controller argument for "App\\Controller\\RecipeController::indexPublic()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecipeRepository".'],
        ], [
            'paginator' => '?',
            'repository' => '?',
        ]);
    }
}
