<?php

namespace ContainerK0q7Nzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CA7BImService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.CA7B_im' shared service.
     *
     * @return \App\Repository\MarkRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecipeController::show()": the $markRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MarkRepository".');
    }
}
