<?php

namespace ContainerK0q7Nzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_R_N8F2BService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.r.n8F2B' shared service.
     *
     * @return \App\Repository\RecipeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RecipeController::index()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RecipeRepository".');
    }
}
