<?php

namespace ContainerK0q7Nzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\FormType' shared autowired service.
     *
     * @return \App\Form\FormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FormType'] = new \App\Form\FormType();
    }
}
