<?php

namespace ContainerK4l5bvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bk3LMfnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bk3LMfn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bk3LMfn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formRepository' => ['privates', 'App\\Repository\\FormRepository', 'getFormRepositoryService', true],
        ], [
            'formRepository' => 'App\\Repository\\FormRepository',
        ]);
    }
}
