<?php

namespace ContainerK4l5bvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KqDvqe2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kqDvqe2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kqDvqe2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.kqDvqe2.App\\Entity\\Post\\Category', NULL, 'Cannot autowire service ".service_locator.kqDvqe2": it needs an instance of "App\\Entity\\Post\\Category" but this type has been excluded in "config/services.yaml".'],
            'postRepository' => ['privates', 'App\\Repository\\Post\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'category' => 'App\\Entity\\Post\\Category',
            'postRepository' => 'App\\Repository\\Post\\PostRepository',
        ]);
    }
}
