<?php

namespace ContainerK4l5bvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kqDvqe2.App\Entity\Post\Category' shared service.
     *
     * @return \App\Entity\Post\Category
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kqDvqe2": it needs an instance of "App\\Entity\\Post\\Category" but this type has been excluded in "config/services.yaml".');
    }
}
