<?php

namespace ContainerK4l5bvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3O7RtAc.App\Entity\Post\Comment' shared service.
     *
     * @return \App\Entity\Post\Comment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3O7RtAc": it needs an instance of "App\\Entity\\Post\\Comment" but this type has been excluded in "config/services.yaml".');
    }
}
