<?php

namespace ContainerK4l5bvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\Post\PostRepository' shared autowired service.
     *
     * @return \App\Repository\Post\PostRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'Post'.\DIRECTORY_SEPARATOR.'PostRepository.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\Post\\PostRepository'])) {
            return $container->privates['App\\Repository\\Post\\PostRepository'];
        }

        return $container->privates['App\\Repository\\Post\\PostRepository'] = new \App\Repository\Post\PostRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), $a);
    }
}
