<?php

namespace ContainerK4l5bvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PhotoRepository' shared autowired service.
     *
     * @return \App\Repository\PhotoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PhotoRepository.php';

        return $container->privates['App\\Repository\\PhotoRepository'] = new \App\Repository\PhotoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
