<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYoWxxAQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYoWxxAQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYoWxxAQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYoWxxAQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYoWxxAQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'YoWxxAQ',
    'container.build_id' => '07d1cc2b',
    'container.build_time' => 1675610241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYoWxxAQ');
