<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhl6yKC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhl6yKC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhl6yKC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhl6yKC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhl6yKC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xhl6yKC',
    'container.build_id' => 'b3fc5d92',
    'container.build_time' => 1679156661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhl6yKC');
