<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Form extends \App\Entity\Form implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Allergies' => [parent::class, 'Allergies', null],
        "\0".parent::class."\0".'Couverts' => [parent::class, 'Couverts', null],
        "\0".parent::class."\0".'Date' => [parent::class, 'Date', null],
        "\0".parent::class."\0".'Heure' => [parent::class, 'Heure', null],
        "\0".parent::class."\0".'Nom' => [parent::class, 'Nom', null],
        "\0".parent::class."\0".'Prenom' => [parent::class, 'Prenom', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Allergies' => [parent::class, 'Allergies', null],
        'Couverts' => [parent::class, 'Couverts', null],
        'Date' => [parent::class, 'Date', null],
        'Heure' => [parent::class, 'Heure', null],
        'Nom' => [parent::class, 'Nom', null],
        'Prenom' => [parent::class, 'Prenom', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
